### ISSUE TITLE
some ZLIB problem?

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/ImageMagick.jl#142] opened 2018-10-27 14:20 UTC
Precompilation of a package that uses ImageMagick resulted in this error. 
```julia 
ERROR: InitError: error compiling __init__: could not load library "/home/yakir/.julia/packages/ImageMagick/d5KBL/deps/usr/lib/libMagickWand-6.Q16.so"
/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/yakir/.julia/packages/ImageMagick/d5KBL/deps/usr/lib/libpng16.so.16)
``` 
I tried to `]up` and `]resolve` and `]build ImageMagick` to no avail.

**Comment by yakir12** [comment] 2018-10-27 18:54
Narrowed it down to a combination of just MATLAB and ImageMagick. I posted a [discourse topic](https://discourse.julialang.org/t/initerror-for-a-combination-of-imagemagick-and-matlab/16869?u=yakir12) about it.

**Comment by timholy** [comment] 2018-10-28 10:11
libz is a bit of a mess right now, see https://github.com/JuliaGraphics/Gtk.jl/pull/387. Try varying the order in which you load packages; e.g., do `using ImageMagick` before anything else.

**Comment by yakir12** [comment] 2018-10-28 19:29
Thanks Tim. I tried that, it doesn't do the trick :/

**Comment by zsz00** [comment] 2018-11-05 05:02
i meet the same trouble ...

**Comment by tknopp** [comment] 2018-11-11 10:36
https://discourse.julialang.org/t/dll-problems-episode-2/12405/12

**Comment by timholy** [comment] 2019-12-12 10:26
Should be fixed on Julia 1.3+

**Closed as completed by timholy** 2019-12-12 10:26 UTC

**Comment by jvanlunenburg** [comment] 2020-06-24 16:57
Why is this closed. I'm on 1.4.2 on CentOS and I can't load a simple test image on a fresh Julia installation. Same error. 
Also mentioned in #133

**Comment by johnnychen94** [comment] 2020-06-24 17:01
Mind to share the codes about how you reproduce the error? And how's your Julia installed, via `yum` or from https://julialang.org/downloads/? It's recommended to install Julia in the latter way.

**Comment by jvanlunenburg** [comment] 2020-06-25 08:59
@johnnychen94 Sure, I just installed a few packages after reading JuliaImages (zlib was pulled in as dependency). Then tried:
```
using Images, TestImages
img = testimage("mandrill")
```
Which gave the error in question.

**Installation**:
I added the Julia repo and used `yum install julia`, then added the IJulia package using the REPL. No errors. 

**My workaround/solution:**
After googling the error, I ran `import ImageMagick` before using Images, that fixed it. Later I discovered a better way: by explicitly installing zlib with `Pkg.add("Zlib_jll")` it created an Artifact that solved the issue.

**Comment by johnnychen94** [comment] 2020-06-25 11:17
Even though it worked for the `IJulia` case, it's still not recommended to install Julia that way. https://julialang.org/downloads/platform/#linux_and_freebsd
> It is strongly recommended that the official generic binaries from the downloads page be used to install Julia on Linux and FreeBSD.
> ...
> The following distribution-specific packages are community contributed. They may not use the right versions of Julia dependencies or include important patches that the official binaries ship with. In general, bug reports will only be accepted if they are reproducible on the official generic binaries on the downloads page.

I can't reproduce that if Julia is installed by extracting the downloads from official releases (the latter way). For a 100% clean build, I use docker as an example.  And I use [jill.py](https://github.com/johnnychen94/jill.py) to install Julia (also the latter way).

<details>
<summary> The complete log </summary>

```
jc@mathai1:~$ docker run -it --rm python:3.6 /bin/bash

root@497d28f030c6:/# 
root@497d28f030c6:/# pip install jill
Collecting jill
  Downloading jill-0.6.13-py3-none-any.whl (30 kB)
Collecting fire
  Downloading fire-0.3.1.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 95 kB/s 
Collecting python-gnupg
  Downloading python_gnupg-0.4.6-py2.py3-none-any.whl (17 kB)
Collecting requests
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 445 kB/s 
Collecting semantic-version
  Downloading semantic_version-2.8.5-py2.py3-none-any.whl (15 kB)
Collecting wget
  Downloading wget-3.2.zip (10 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 1.0 MB/s 
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 2.1 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.6 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 2.2 MB/s 
Building wheels for collected packages: fire, wget, termcolor
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.3.1-py2.py3-none-any.whl size=111005 sha256=fcb9fd718987d562d7c940b1ea0d8669c7bb7a17010273aab92457b553bd7f0e
  Stored in directory: /root/.cache/pip/wheels/3e/38/8f/e5bd4465e4b72c8e4d1530ac46e1a42e1d2495f8c93242d5f1
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9681 sha256=1142e50ffc299fcd6294e705fb4ebb7158c204ee1c9d924001c61771922fadc2
  Stored in directory: /root/.cache/pip/wheels/90/1d/93/c863ee832230df5cfc25ca497b3e88e0ee3ea9e44adc46ac62
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=64e4f2a5c3486d852d2fbff41bdba6677f33bc0e54afbf6177e2d08f0a650861
  Stored in directory: /root/.cache/pip/wheels/93/2a/eb/e58dbcbc963549ee4f065ff80a59f274cc7210b6eab962acdc
Successfully built fire wget termcolor
Installing collected packages: six, termcolor, fire, python-gnupg, urllib3, chardet, idna, certifi, requests, semantic-version, wget, jill
Successfully installed certifi-2020.6.20 chardet-3.0.4 fire-0.3.1 idna-2.9 jill-0.6.13 python-gnupg-0.4.6 requests-2.24.0 semantic-version-2.8.5 six-1.15.0 termcolor-1.1.0 urllib3-1.25.9 wget-3.2
root@497d28f030c6:/# jill install 1.4.2 --confirm
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

----- Download Julia -----
downloading Julia release for 1.4.2-linux-x86_64
downloading from https://mirrors.bfsu.edu.cn/julia-releases/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz
100% [........................................................................] 99093958 / 99093958
finished downloading julia-1.4.2-linux-x86_64.tar.gz
downloading from https://mirrors.bfsu.edu.cn/julia-releases/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz.asc
100% [..................................................................................] 866 / 866
finished downloading julia-1.4.2-linux-x86_64.tar.gz.asc
verifying 1.4.2-linux-x86_64 succeed
----- Install Julia -----
install Julia to /opt/julias/julia-1.4
make new symlink /usr/local/bin/julia-1
make new symlink /usr/local/bin/julia-1.4
make new symlink /usr/local/bin/julia
----- Post Installation -----
remove downloaded files...
remove /julia-1.4.2-linux-x86_64.tar.gz
remove /julia-1.4.2-linux-x86_64.tar.gz.asc
Done!
root@497d28f030c6:/# julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> add Images TestImages ImageMagick
    Cloning default registries into `~/.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
      Added registry `General` to `~/.julia/registries/General`
  Resolving package versions...
    Cloning [916415d5-f1e6-5110-898d-aaa5f9f070e0] Images from https://github.com/JuliaImages/Images.jl.git
  Installed Images ─────────────────────── v0.22.3
    Cloning [b53b4c65-9356-5827-b1ea-8c7a1a84506f] libpng_jll from https://github.com/JuliaBinaryWrappers/libpng_jll.jl.git
  Installed libpng_jll ─────────────────── v1.6.37+3
    Cloning [1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0] IntelOpenMP_jll from https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl.git
  Installed IntelOpenMP_jll ────────────── v2018.0.3+0
    Cloning [5e47fb64-e119-507b-a336-dd2b206d9990] TestImages from https://github.com/JuliaImages/TestImages.jl.git
  Installed TestImages ─────────────────── v1.0.3
    Cloning [6218d12a-5da1-5696-b52f-db25d2ecc6d1] ImageMagick from https://github.com/JuliaIO/ImageMagick.jl.git
  Installed ImageMagick ────────────────── v1.1.5
    Cloning [3161d3a3-bdf6-5164-811a-617609db77b4] Zstd_jll from https://github.com/JuliaBinaryWrappers/Zstd_jll.jl.git
  Installed Zstd_jll ───────────────────── v1.4.5+0
    Cloning [9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a] DataAPI from https://github.com/JuliaData/DataAPI.jl.git
  Installed DataAPI ────────────────────── v1.3.0
    Cloning [c3611d14-8923-5661-9e6a-0046d554d3a4] ColorVectorSpace from https://github.com/JuliaGraphics/ColorVectorSpace.jl.git
  Installed ColorVectorSpace ───────────── v0.8.5
    Cloning [3a884ed6-31ef-47d7-9d2a-63182c4928ed] UnPack from https://github.com/mauro3/UnPack.jl.git
  Installed UnPack ─────────────────────── v1.0.1
    Cloning [787d08f9-d448-5407-9aad-5290dd7ab264] ImageMorphology from https://github.com/JuliaImages/ImageMorphology.jl.git
  Installed ImageMorphology ────────────── v0.2.6
    Cloning [efe28fd5-8261-553b-a9e1-b2916fc3738e] OpenSpecFun_jll from https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git
  Installed OpenSpecFun_jll ────────────── v0.5.3+3
    Cloning [9b13fd28-a010-5f03-acff-a1bbcff69959] IndirectArrays from https://github.com/JuliaArrays/IndirectArrays.jl.git
  Installed IndirectArrays ─────────────── v0.5.1
    Cloning [b3c3ace0-ae52-54e7-9d0b-2c1406fd6b9d] RangeArrays from https://github.com/JuliaArrays/RangeArrays.jl.git
  Installed RangeArrays ────────────────── v0.3.2
    Cloning [8197267c-284f-5f27-9208-e0e47529a953] IntervalSets from https://github.com/JuliaMath/IntervalSets.jl.git
  Installed IntervalSets ───────────────── v0.5.1
    Cloning [c8e1da08-722c-5040-9ed9-7db0dc04731e] IterTools from https://github.com/JuliaCollections/IterTools.jl.git
  Installed IterTools ──────────────────── v1.3.0
    Cloning [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91] StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
  Installed StatsBase ──────────────────── v0.33.0
    Cloning [06e1c1a7-607b-532d-9fad-de7d9aa2abac] TiledIteration from https://github.com/JuliaArrays/TiledIteration.jl.git
  Installed TiledIteration ─────────────── v0.2.4
    Cloning [856f044c-d86e-5d09-b602-aeab76dc8ba7] MKL_jll from https://github.com/JuliaBinaryWrappers/MKL_jll.jl.git
  Installed MKL_jll ────────────────────── v2020.1.216+0
    Cloning [13072b0f-2c55-5437-9ae7-d433b7a33950] AxisAlgorithms from https://github.com/timholy/AxisAlgorithms.jl.git
  Installed AxisAlgorithms ─────────────── v1.0.0
    Cloning [efce3f68-66dc-5838-9240-27a6d6f5f9b6] WoodburyMatrices from https://github.com/timholy/WoodburyMatrices.jl.git
  Installed WoodburyMatrices ───────────── v0.5.2
    Cloning [4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd] FFTViews from https://github.com/JuliaArrays/FFTViews.jl.git
  Installed FFTViews ───────────────────── v0.3.1
    Cloning [51556ac3-7006-55f5-8cb3-34580c88182d] ImageDistances from https://github.com/JuliaImages/ImageDistances.jl.git
  Installed ImageDistances ─────────────── v0.2.7
    Cloning [5432bcbf-9aad-5242-b902-cca2824c8663] PaddedViews from https://github.com/JuliaArrays/PaddedViews.jl.git
  Installed PaddedViews ────────────────── v0.5.5
    Cloning [e94cdb99-869f-56ef-bcf0-1ae2bcbe0389] MosaicViews from https://github.com/JuliaArrays/MosaicViews.jl.git
  Installed MosaicViews ────────────────── v0.2.2
    Cloning [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8] DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
  Installed DataStructures ─────────────── v0.17.18
    Cloning [f332f351-ec65-5f6a-b3d1-319c6670881a] ImageContrastAdjustment from https://github.com/JuliaImages/ImageContrastAdjustment.jl.git
  Installed ImageContrastAdjustment ────── v0.3.5
    Cloning [6a3955dd-da59-5b1f-98d4-e7296123deb5] ImageFiltering from https://github.com/JuliaImages/ImageFiltering.jl.git
  Installed ImageFiltering ─────────────── v0.6.13
    Cloning [5ae59095-9a9b-59fe-a467-6f913c188581] Colors from https://github.com/JuliaGraphics/Colors.jl.git
  Installed Colors ─────────────────────── v0.12.2
    Cloning [a09fc81d-aa75-5fe9-8630-4744c3626534] ImageCore from https://github.com/JuliaImages/ImageCore.jl.git
  Installed ImageCore ──────────────────── v0.8.14
    Cloning [2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac] ImageAxes from https://github.com/JuliaImages/ImageAxes.jl.git
  Installed ImageAxes ──────────────────── v0.6.4
    Cloning [da5c29d0-fa7d-589e-88eb-ea29b0a81949] EllipsisNotation from https://github.com/ChrisRackauckas/EllipsisNotation.jl.git
  Installed EllipsisNotation ───────────── v0.4.0
    Cloning [bc367c6b-8a6b-528e-b4bd-a4b897500b49] ImageMetadata from https://github.com/JuliaImages/ImageMetadata.jl.git
  Installed ImageMetadata ──────────────── v0.9.1
    Cloning [a2af1166-a08f-5f64-846c-94a0d3cef48c] SortingAlgorithms from https://github.com/JuliaCollections/SortingAlgorithms.jl.git
  Installed SortingAlgorithms ──────────── v0.3.1
    Cloning [02fcd773-0e25-5acc-982a-7f6622650795] ImageTransformations from https://github.com/JuliaImages/ImageTransformations.jl.git
  Installed ImageTransformations ───────── v0.8.4
    Cloning [4e3cecfd-b093-5904-9786-8bbb286a6a31] ImageShow from https://github.com/JuliaImages/ImageShow.jl.git
  Installed ImageShow ──────────────────── v0.2.3
    Cloning [1914dd2f-81c6-5fcd-8719-6d5c9610ff09] MacroTools from https://github.com/MikeInnes/MacroTools.jl.git
  Installed MacroTools ─────────────────── v0.5.5
    Cloning [bac558e1-5e72-5ebc-8fee-abe8a469f55d] OrderedCollections from https://github.com/JuliaCollections/OrderedCollections.jl.git
  Installed OrderedCollections ─────────── v1.2.0
    Cloning [a2bd30eb-e257-5431-a919-1863eab51364] Graphics from https://github.com/JuliaGraphics/Graphics.jl.git
  Installed Graphics ───────────────────── v1.0.2
    Cloning [ed09eef8-17a6-5b46-8889-db040fac31e3] ComputationalResources from https://github.com/timholy/ComputationalResources.jl.git
  Installed ComputationalResources ─────── v0.3.2
    Cloning [53c48c17-4a7d-5ca2-90c5-79b7896eea93] FixedPointNumbers from https://github.com/JuliaMath/FixedPointNumbers.jl.git
  Installed FixedPointNumbers ──────────── v0.8.1
    Cloning [189a3867-3050-52da-a836-e630ba90ab69] Reexport from https://github.com/simonster/Reexport.jl.git
  Installed Reexport ───────────────────── v0.2.0
    Cloning [bbac6d45-d8f3-5730-bfe4-7a449cd117ca] IdentityRanges from https://github.com/JuliaArrays/IdentityRanges.jl.git
  Installed IdentityRanges ─────────────── v0.3.1
    Cloning [90137ffa-7385-5640-81b9-e52037218182] StaticArrays from https://github.com/JuliaArrays/StaticArrays.jl.git
  Installed StaticArrays ───────────────── v0.12.3
    Cloning [2996bd0c-7a13-11e9-2da2-2f5ce47296a9] ImageQualityIndexes from https://github.com/JuliaImages/ImageQualityIndexes.jl.git
  Installed ImageQualityIndexes ────────── v0.1.4
    Cloning [699a6c99-e7fa-54fc-8d76-47d257e15c1d] SimpleTraits from https://github.com/mauro3/SimpleTraits.jl.git
  Installed SimpleTraits ───────────────── v0.9.2
    Cloning [e66e0078-7015-5450-92f7-15fbd957f2ae] CompilerSupportLibraries_jll from https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl.git
  Installed CompilerSupportLibraries_jll ─ v0.3.3+0
    Cloning [6fe1bfb0-de20-5000-8ca7-80f57d26f881] OffsetArrays from https://github.com/JuliaArrays/OffsetArrays.jl.git
  Installed OffsetArrays ───────────────── v1.1.0
    Cloning [77ba4419-2d1f-58cd-9bb1-8ffee604a2e3] NaNMath from https://github.com/mlubin/NaNMath.jl.git
  Installed NaNMath ────────────────────── v0.3.3
    Cloning [89763e89-9b03-5906-acba-b20f662cd828] Libtiff_jll from https://github.com/JuliaBinaryWrappers/Libtiff_jll.jl.git
  Installed Libtiff_jll ────────────────── v4.1.0+0
    Cloning [d96e819e-fc66-5662-9728-84c9c7592b0a] Parameters from https://github.com/mauro3/Parameters.jl.git
  Installed Parameters ─────────────────── v0.12.1
    Cloning [e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28] Missings from https://github.com/JuliaData/Missings.jl.git
  Installed Missings ───────────────────── v0.4.3
    Cloning [c84ed2f1-dad5-54f0-aa8e-dbefe2724439] Ratios from https://github.com/timholy/Ratios.jl.git
  Installed Ratios ─────────────────────── v0.4.0
    Cloning [6038ab10-8711-5258-84ad-4b1120ba62dc] Rotations from https://github.com/JuliaGeometry/Rotations.jl.git
  Installed Rotations ──────────────────── v0.13.0
    Cloning [83775a58-1f1d-513f-b197-d71354ab007a] Zlib_jll from https://github.com/JuliaBinaryWrappers/Zlib_jll.jl.git
  Installed Zlib_jll ───────────────────── v1.2.11+13
    Cloning [dc8bdbbb-1ca9-579f-8c36-e416f6a65cce] CustomUnitRanges from https://github.com/JuliaArrays/CustomUnitRanges.jl.git
  Installed CustomUnitRanges ───────────── v1.0.0
    Cloning [5789e2e9-d7fb-5bc7-8068-2c6fae9b9549] FileIO from https://github.com/JuliaIO/FileIO.jl.git
  Installed FileIO ─────────────────────── v1.3.0
    Cloning [39de3d68-74b9-583c-8d2d-e117c070f3a9] AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
  Installed AxisArrays ─────────────────── v0.4.3
    Cloning [c73af94c-d91f-53ed-93a7-00f77d67a9d7] ImageMagick_jll from https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl.git
  Installed ImageMagick_jll ────────────── v6.9.10-12+3
    Cloning [276daf66-3868-5448-9aa4-cd146d93841b] SpecialFunctions from https://github.com/JuliaMath/SpecialFunctions.jl.git
  Installed SpecialFunctions ───────────── v0.10.3
    Cloning [621f4979-c628-5d54-868e-fcf4e3e8185c] AbstractFFTs from https://github.com/JuliaMath/AbstractFFTs.jl.git
  Installed AbstractFFTs ───────────────── v0.5.0
    Cloning [a98d9a8b-a2ab-59e6-89dd-64a1c18fca59] Interpolations from https://github.com/JuliaMath/Interpolations.jl.git
  Installed Interpolations ─────────────── v0.12.10
    Cloning [aacddb02-875f-59d6-b918-886e6ef4fbf8] JpegTurbo_jll from https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl.git
  Installed JpegTurbo_jll ──────────────── v2.0.1+0
    Cloning [aafaddc9-749c-510e-ac4f-586e18779b91] CatIndices from https://github.com/JuliaArrays/CatIndices.jl.git
  Installed CatIndices ─────────────────── v0.2.1
    Cloning [7a1cc6ca-52ef-59f5-83cd-3a7055c09341] FFTW from https://github.com/JuliaMath/FFTW.jl.git
  Installed FFTW ───────────────────────── v1.2.2
    Cloning [150eb455-5306-5404-9cee-2592286d6298] CoordinateTransformations from https://github.com/JuliaGeometry/CoordinateTransformations.jl.git
  Installed CoordinateTransformations ──── v0.5.1
    Cloning [3da002f7-5984-5a60-b8a6-cbb66c0b333f] ColorTypes from https://github.com/JuliaGraphics/ColorTypes.jl.git
  Installed ColorTypes ─────────────────── v0.10.4
    Cloning [ae029012-a4dd-5104-9daa-d747884805df] Requires from https://github.com/MikeInnes/Requires.jl.git
  Installed Requires ───────────────────── v1.0.1
    Cloning [b4f34e82-e78d-54a5-968a-f98e89d6e8f7] Distances from https://github.com/JuliaStats/Distances.jl.git
  Installed Distances ──────────────────── v0.8.2
    Cloning [f5851436-0d7a-5f13-b9de-f02708fd171a] FFTW_jll from https://github.com/JuliaBinaryWrappers/FFTW_jll.jl.git
  Installed FFTW_jll ───────────────────── v3.3.9+5
    Cloning [dbb5928d-eab1-5f90-85c2-b9b0edb7c900] MappedArrays from https://github.com/JuliaArrays/MappedArrays.jl.git
  Installed MappedArrays ───────────────── v0.2.2
Downloading artifact: libpng
Downloading artifact: Zstd
Downloading artifact: IntelOpenMP
Downloading artifact: OpenSpecFun
Downloading artifact: CompilerSupportLibraries
Downloading artifact: Libtiff
Downloading artifact: Zlib
Downloading artifact: ImageMagick
Downloading artifact: JpegTurbo
Downloading artifact: FFTW
   Updating `~/.julia/environments/v1.4/Project.toml`
  [6218d12a] + ImageMagick v1.1.5
  [916415d5] + Images v0.22.3
  [5e47fb64] + TestImages v1.0.3
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [621f4979] + AbstractFFTs v0.5.0
  [13072b0f] + AxisAlgorithms v1.0.0
  [39de3d68] + AxisArrays v0.4.3
  [aafaddc9] + CatIndices v0.2.1
  [3da002f7] + ColorTypes v0.10.4
  [c3611d14] + ColorVectorSpace v0.8.5
  [5ae59095] + Colors v0.12.2
  [e66e0078] + CompilerSupportLibraries_jll v0.3.3+0
  [ed09eef8] + ComputationalResources v0.3.2
  [150eb455] + CoordinateTransformations v0.5.1
  [dc8bdbbb] + CustomUnitRanges v1.0.0
  [9a962f9c] + DataAPI v1.3.0
  [864edb3b] + DataStructures v0.17.18
  [b4f34e82] + Distances v0.8.2
  [da5c29d0] + EllipsisNotation v0.4.0
  [4f61f5a4] + FFTViews v0.3.1
  [7a1cc6ca] + FFTW v1.2.2
  [f5851436] + FFTW_jll v3.3.9+5
  [5789e2e9] + FileIO v1.3.0
  [53c48c17] + FixedPointNumbers v0.8.1
  [a2bd30eb] + Graphics v1.0.2
  [bbac6d45] + IdentityRanges v0.3.1
  [2803e5a7] + ImageAxes v0.6.4
  [f332f351] + ImageContrastAdjustment v0.3.5
  [a09fc81d] + ImageCore v0.8.14
  [51556ac3] + ImageDistances v0.2.7
  [6a3955dd] + ImageFiltering v0.6.13
  [6218d12a] + ImageMagick v1.1.5
  [c73af94c] + ImageMagick_jll v6.9.10-12+3
  [bc367c6b] + ImageMetadata v0.9.1
  [787d08f9] + ImageMorphology v0.2.6
  [2996bd0c] + ImageQualityIndexes v0.1.4
  [4e3cecfd] + ImageShow v0.2.3
  [02fcd773] + ImageTransformations v0.8.4
  [916415d5] + Images v0.22.3
  [9b13fd28] + IndirectArrays v0.5.1
  [1d5cc7b8] + IntelOpenMP_jll v2018.0.3+0
  [a98d9a8b] + Interpolations v0.12.10
  [8197267c] + IntervalSets v0.5.1
  [c8e1da08] + IterTools v1.3.0
  [aacddb02] + JpegTurbo_jll v2.0.1+0
  [89763e89] + Libtiff_jll v4.1.0+0
  [856f044c] + MKL_jll v2020.1.216+0
  [1914dd2f] + MacroTools v0.5.5
  [dbb5928d] + MappedArrays v0.2.2
  [e1d29d7a] + Missings v0.4.3
  [e94cdb99] + MosaicViews v0.2.2
  [77ba4419] + NaNMath v0.3.3
  [6fe1bfb0] + OffsetArrays v1.1.0
  [efe28fd5] + OpenSpecFun_jll v0.5.3+3
  [bac558e1] + OrderedCollections v1.2.0
  [5432bcbf] + PaddedViews v0.5.5
  [d96e819e] + Parameters v0.12.1
  [b3c3ace0] + RangeArrays v0.3.2
  [c84ed2f1] + Ratios v0.4.0
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v1.0.1
  [6038ab10] + Rotations v0.13.0
  [699a6c99] + SimpleTraits v0.9.2
  [a2af1166] + SortingAlgorithms v0.3.1
  [276daf66] + SpecialFunctions v0.10.3
  [90137ffa] + StaticArrays v0.12.3
  [2913bbd2] + StatsBase v0.33.0
  [5e47fb64] + TestImages v1.0.3
  [06e1c1a7] + TiledIteration v0.2.4
  [3a884ed6] + UnPack v1.0.1
  [efce3f68] + WoodburyMatrices v0.5.2
  [83775a58] + Zlib_jll v1.2.11+13
  [3161d3a3] + Zstd_jll v1.4.5+0
  [b53b4c65] + libpng_jll v1.6.37+3
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
   Building TestImages → `~/.julia/packages/TestImages/H1Voj/deps/build.log`
   Building FFTW ──────→ `~/.julia/packages/FFTW/kcXL6/deps/build.log`

julia> using Images, TestImages
[ Info: Precompiling Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]

julia> img = testimage("mandrill");
[ Info: Precompiling ImageMagick [6218d12a-5da1-5696-b52f-db25d2ecc6d1]

julia> 
```

</details>

We haven't observed any similar reports since Julia 1.3 has brought the [Artifacts](https://julialang.org/blog/2019/11/artifacts/) feature to the ecosystem, this issue was closed because we had upgraded ImageMagick with this feature. For this reason, I highly recommend you to try installing Julia from official downloads, and see if it still gives you the same error.

Also, for a clean test, you might also want to modify the `JULIA_DEPOT_PATH` to an empty folder so that you don't get accidentally affected by old packages. For example: `JULIA_DEPOT_PATH=/tmp/pkgs julia` will put all related downloads to that specific folder.
